import{a as d,S as E,A as w}from"./assets/vendor-DjtasW9M.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))i(n);new MutationObserver(n=>{for(const s of n)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(n){const s={};return n.integrity&&(s.integrity=n.integrity),n.referrerPolicy&&(s.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?s.credentials="include":n.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(n){if(n.ep)return;n.ep=!0;const s=r(n);fetch(n.href,s)}})();const S="https://events-store.b.goit.study/api",l={CATEGORIES:"/categories",EVENTS:"/events",LIMIT:8};d.defaults.baseURL=S;async function I(){return(await d.get(l.CATEGORIES)).data}async function g(t=1,e=""){return e==="all"||!e?(await d.get(`${l.EVENTS}?page=${t}&limit=${l.LIMIT}`)).data:(await d.get(`${l.EVENTS}?page=${t}&limit=${l.LIMIT}&category=${e}`)).data}const o={categoriesListEl:document.querySelector(".js-event-category-list"),categoriesListOpenSvgBtn:document.querySelector(".icon-rotate"),caregoryListSelect:document.querySelector(".event-category-select"),categoriesListOpen:document.querySelector(".event-category-list"),eventsList:document.querySelector(".events-list"),firstCategoryButton:document.querySelector(".categories__btn"),showMoreBtn:document.querySelector(".show-more-btn"),loader:document.querySelector(".loader"),eventDetailsBtn:document.querySelector(".event-details-btn")};function $(t,e){const r=t%4,i=t-r;return r===0||e<i?"row-of-4":r===3?"row-last-3":r===2?"row-last-2":r===1?"row-last-1":""}function f(){o.loader.classList.remove("is-hidden")}function y(){o.loader.classList.add("is-hidden")}function b(t){const e=[{_id:"all",name:"Всі події",tags:[]},...t],r=e.map(({_id:i,name:n,tags:s},a)=>{const m=$(e.length,a),L=s.map(h=>`#${h}, `).join("");return`<li class="event-category-item ${m}" data-category="${i}">
          <p class="event-category-title">${n}</p>
          <p class="event-category-tags">${L}</p>
        </li>`}).join("");o.categoriesListEl.innerHTML=r,o.firstCategoryButton&&o.firstCategoryButton.classList.add("categories__btn--active"),window.innerWidth<768&&!o.categoriesListEl.SimpleBar&&new E(o.categoriesListEl,{autoHide:!1})}o.caregoryListSelect.addEventListener("click",C);function C(t){o.categoriesListOpenSvgBtn.classList.toggle("icon-rotate-rotated"),o.categoriesListOpen.classList.toggle("is-hidden")}function v(t){const e=t.map(({_id:r,name:i,price:n,category:s,image:a})=>`<li class="event-item">
        <img
          src="${a}"
          alt="${i}"
          width="335"
          height="251"
        />
        <div class="event-info">
          <p class="event-title">${i}</p>
          <p class="event-text">${s.name}</p>
          <p class="event-price">від ${n.value} грн</p>
        </div>
        <button type="button" class="event-details-btn" data-event-id="${r}">Детальніше</button>
      </li>`).join("");o.eventsList.insertAdjacentHTML("beforeend",e)}let c=1,u="all";async function M(){try{f();const t=await I();b(t);const{events:e,totalItems:r}=await g(c,u);v(e),p(r)}catch(t){console.log("error events list",t)}finally{y()}}async function B(t){const e=t.target.closest(".event-category-item");if(e)try{u=e.dataset.category,c=1,o.eventsList.innerHTML="",f();const{events:i,totalItems:n}=await g(c,u);v(i),p(n)}catch(r){console.log("error during getting events by category",r)}finally{y()}}async function O(t){c+=1;try{f();const{events:e,totalItems:r}=await g(c,u);v(e),p(r)}catch(e){console.log("error during getting more events by category",e),c-=1}finally{y()}}function p(t){o.showMoreBtn.disabled=c*l.LIMIT>=t}function T(t){const e=t.target.dataset.eventId;e&&console.log(e)}document.addEventListener("DOMContentLoaded",M);o.categoriesListEl.addEventListener("click",B);o.showMoreBtn.addEventListener("click",O);o.eventsList.addEventListener("click",T);new w(".accordion-container",{showMultiple:!1});
//# sourceMappingURL=index.js.map
